namespace Tabliq.Sql.Core;

public enum SyntaxKind
{
    // Tokens
    BadToken,
    EndOfFileToken,
    IdentifierToken,
    ParameterToken,
    NumberToken,
    StringToken,
    CommaToken,
    DotToken,
    StarToken,
    OpenParenToken,
    CloseParenToken,
    EqualsToken,
    NotEqualsToken,
    LessToken,
    GreaterToken,
    LessOrEqualsToken,
    GreaterOrEqualsToken,
    PlusToken,
    MinusToken,
    SlashToken,

    // Keywords
    SelectKeyword,
    FromKeyword,
    WhereKeyword,
    WithKeyword,
    AsKeyword,
    IsKeyword,
    InKeyword,
    UnionKeyword,
    AllKeyword,
    DistinctKeyword,
    TopKeyword,
    JoinKeyword,
    OnKeyword,
    OverKeyword,
    OrderKeyword,
    PartitionKeyword,
    ByKeyword,
    GroupKeyword,
    HavingKeyword,
    RowKeyword,
    RangeKeyword,
    OffsetKeyword,
    RowsKeyword,
    FetchKeyword,
    NextKeyword,
    FirstKeyword,
    OnlyKeyword,
    // order by direction keywords
    AscKeyword,
    DescKeyword,

    // should these be contextual keywords handled in the lexer?? for joins?
    InnerKeyword,
    OuterKeyword,
    LeftKeyword,
    RightKeyword,
    FullKeyword,
    CrossKeyword,
    OrKeyword,
    AndKeyword,
    NotKeyword,
    NullKeyword,
    LikeKeyword,
    CaseKeyword,
    WhenKeyword,
    ThenKeyword,
    ElseKeyword,
    EndKeyword,
    PipePipeToken,
    ExistsKeyword,

    //// Nodes
    //CompilationUnit,
    //SqlScript,
    //SelectStatement,
    //FromClause,
    //WhereClause,
    //IdentifierName,
    //LiteralExpression,
    //BinaryExpression,
    //ColumnList,
    //StarExpression,
    //CommonTableExpression,
    //SelectExpression,
    //SelectProjection,
    //UnionStatement,
    //BadStatement,
    //NamedTableReference,
    //SubSelectTableReference,
    //IdentiferExpression,
    //IdentifierExpression,
    //AsExpression,
    //BracketedExpression,
    //EmptyExpression,
    //JoinClause,
    //BadTableReference,
}
