using System;
using System.Collections.Generic;
using System.Text;
using Tabliq.Sql.Ast;
using Tabliq.Sql.Core;

namespace Tabliq.Execution.Functions;

public static class BuiltinFunctions
{
    public static IEnumerable<SqlFunction> BuiltingFunctions { get; } = [
            new CountFunction(),
            new AvgFunction(),
            new MonthFunction(),
            new YearFunction(),
            new DayFunction(),
            new RightFunction(),
            new LeftFunction(),
            new PositionFunction(),
            new SumFunction(),
             new PassThroughValueFunction("DATE_BUCKET",
                SqlFunctionArgs.Arg("datepart", skipBinding: true),
                SqlFunctionArgs.Arg("number"),
                SqlFunctionArgs.Arg("date"),
                SqlFunctionArgs.Arg("origin", optional: true)),
            new PassThroughValueFunction("DATEADD",
                SqlFunctionArgs.Arg("datepart", skipBinding: true),
                SqlFunctionArgs.Arg("count"),
                SqlFunctionArgs.Arg("date")),
            new PassThroughValueFunction("DATEDIFF",
                SqlFunctionArgs.Arg("datepart", skipBinding: true),
                SqlFunctionArgs.Arg("startDate"),
                SqlFunctionArgs.Arg("endDate")),
            new PassThroughValueFunction("DATEDIFF_BIG",
                SqlFunctionArgs.Arg("datepart", skipBinding: true),
                SqlFunctionArgs.Arg("startDate"),
                SqlFunctionArgs.Arg("endDate")),
            new PassThroughValueFunction("DATEFROMPARTS",
                SqlFunctionArgs.Arg("year"),
                SqlFunctionArgs.Arg("month"),
                SqlFunctionArgs.Arg("day")),
            new PassThroughValueFunction("DATENAME",
                SqlFunctionArgs.Arg("datepart", skipBinding: true),
                SqlFunctionArgs.Arg("date")),
            new PassThroughValueFunction("DATEPART",
                SqlFunctionArgs.Arg("datepart", skipBinding: true),
                SqlFunctionArgs.Arg("date")),
            new PassThroughValueFunction("DATETIME2FROMPARTS",
                SqlFunctionArgs.Arg("year"),
                SqlFunctionArgs.Arg("month"),
                SqlFunctionArgs.Arg("day"),
                SqlFunctionArgs.Arg("hour"),
                SqlFunctionArgs.Arg("minute"),
                SqlFunctionArgs.Arg("second"),
                SqlFunctionArgs.Arg("fractions"),
                SqlFunctionArgs.Arg("precision")),
            new PassThroughValueFunction("DATETIMEFROMPARTS",
                SqlFunctionArgs.Arg("year"),
                SqlFunctionArgs.Arg("month"),
                SqlFunctionArgs.Arg("day"),
                SqlFunctionArgs.Arg("hour"),
                SqlFunctionArgs.Arg("minute"),
                SqlFunctionArgs.Arg("second"),
                SqlFunctionArgs.Arg("milliseconds")),
            new PassThroughValueFunction("DATETIMEOFFSETFROMPARTS",
                SqlFunctionArgs.Arg("year"),
                SqlFunctionArgs.Arg("month"),
                SqlFunctionArgs.Arg("day"),
                SqlFunctionArgs.Arg("hour"),
                SqlFunctionArgs.Arg("minute"),
                SqlFunctionArgs.Arg("second"),
                SqlFunctionArgs.Arg("fractions"),
                SqlFunctionArgs.Arg("hour_offset"),
                SqlFunctionArgs.Arg("minute_offset"),
                SqlFunctionArgs.Arg("precision")),
            new PassThroughValueFunction("SMALLDATETIMEFROMPARTS",
                SqlFunctionArgs.Arg("year"),
                SqlFunctionArgs.Arg("month"),
                SqlFunctionArgs.Arg("day"),
                SqlFunctionArgs.Arg("hour"),
                SqlFunctionArgs.Arg("minute")),
            new PassThroughValueFunction("SWITCHOFFSET",
                SqlFunctionArgs.Arg("datetimeoffset_expression"),
                SqlFunctionArgs.Arg("timezoneoffset_expression")),
            new PassThroughValueFunction("TIMEFROMPARTS",
                SqlFunctionArgs.Arg("hour"),
                SqlFunctionArgs.Arg("minute"),
                SqlFunctionArgs.Arg("second"),
                SqlFunctionArgs.Arg("fractions"),
                SqlFunctionArgs.Arg("precision")),
            new PassThroughValueFunction("TODATETIMEOFFSET",
                SqlFunctionArgs.Arg("datetimeoffset_expression"),
                SqlFunctionArgs.Arg("timezoneoffset_expression")),
            new PassThroughValueFunction("DATETRUNC",
                SqlFunctionArgs.Arg("datepart", skipBinding: true),
                SqlFunctionArgs.Arg("date")),
            new PassThroughValueFunction("EOMONTH",
                SqlFunctionArgs.Arg("start_date"),
                SqlFunctionArgs.Arg("month_to_add", optional: true)),
            new PassThroughValueFunction("GETDATE", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("GETUTCDATE", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("ISDATE", SqlFunctionArgs.Arg("date")),
            new PassThroughValueFunction("SYSDATETIME", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("SYSDATETIMEOFFSET", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("SYSUTCDATETIME", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughAggregateFunction("COUNT_BIG", SqlFunctionArgs.Arg("expression")),
            new PassThroughAggregateFunction("PRODUCT", SqlFunctionArgs.Arg("expression")),
            new PassThroughAggregateFunction("STDEV", SqlFunctionArgs.Arg("expression")),
            new PassThroughAggregateFunction("STDEVP", SqlFunctionArgs.Arg("expression")),
            new PassThroughAggregateFunction("VAR", SqlFunctionArgs.Arg("expression")),
            new PassThroughAggregateFunction("VARP", SqlFunctionArgs.Arg("expression")),
            new PassThroughValueFunction("CUME_DIST", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("FIRST_VALUE", SqlFunctionArgs.Arg("scalar_expression", optional: true)),
            new PassThroughValueFunction("PERCENT_RANK", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("LAG",
                SqlFunctionArgs.Arg("scalar_expression"),
                SqlFunctionArgs.Arg("offset", optional: true),
                SqlFunctionArgs.Arg("default", optional: true)),
            new PassThroughValueFunction("LAST_VALUE", SqlFunctionArgs.Arg("scalar_expression", optional: true)),
            new PassThroughValueFunction("LEAD",
                SqlFunctionArgs.Arg("scalar_expression"),
                SqlFunctionArgs.Arg("offset", optional: true),
                SqlFunctionArgs.Arg("default", optional: true)),
            new PassThroughValueFunction("PERCENTILE_CONT", SqlFunctionArgs.Arg("numeric_literal")),
            new PassThroughValueFunction("PERCENTILE_DISC", SqlFunctionArgs.Arg("numeric_literal")),
            new PassThroughValueFunction("ABS", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("ACOS", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("ASIN", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("ATAN", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("ATN2", SqlFunctionArgs.Arg("x"), SqlFunctionArgs.Arg("y")),
            new PassThroughValueFunction("COS", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("COT", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("DEGREES", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("EXP", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("FLOOR", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("LOG", SqlFunctionArgs.Arg("numeric_expression"), SqlFunctionArgs.Arg("base", optional: true)),
            new PassThroughValueFunction("LOG10", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("PI", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("POWER", SqlFunctionArgs.Arg("numeric_expression"), SqlFunctionArgs.Arg("exponent")),
            new PassThroughValueFunction("RADIANS", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("RAND", SqlFunctionArgs.Arg("seed", optional: true)),
            new PassThroughValueFunction("ROUND", SqlFunctionArgs.Arg("numeric_expression"), SqlFunctionArgs.Arg("length"), SqlFunctionArgs.Arg("function", optional: true)),
            new PassThroughValueFunction("SIGN", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("SIN", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("SQRT", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("SQUARE", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("TAN", SqlFunctionArgs.Arg("numeric_expression")),
            new PassThroughValueFunction("GREATEST", [SqlFunctionArgs.Arg("numeric_expression")], SqlFunctionArgs.ParamsArg("numeric_expression")),
            new PassThroughValueFunction("LEAST", [SqlFunctionArgs.Arg("numeric_expression")], SqlFunctionArgs.ParamsArg("numeric_expression")),
            new PassThroughValueFunction("IIF", [SqlFunctionArgs.Arg("boolean_expression"), SqlFunctionArgs.Arg("true_value"), SqlFunctionArgs.Arg("false_value")]),
            new PassThroughValueFunction("DENSE_RANK", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("NTILE", SqlFunctionArgs.Arg("integer_expression")),
            new PassThroughValueFunction("RANK", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("ROW_NUMBER", Array.Empty<SqlFunction.FunctionArgument>()),
            new PassThroughValueFunction("ASCII", SqlFunctionArgs.Arg("character_expression")),
            new PassThroughValueFunction("CHAR", SqlFunctionArgs.Arg("integer_expression")),
            new PassThroughValueFunction("CHARINDEX", SqlFunctionArgs.Arg("expression_to_find"), SqlFunctionArgs.Arg("expression_to_search"), SqlFunctionArgs.Arg("start_location", optional: true)),
            new PassThroughValueFunction("CONCAT", [SqlFunctionArgs.Arg("arg1")], SqlFunctionArgs.ParamsArg("argOthers")),
            new PassThroughValueFunction("CONCAT_WS", [SqlFunctionArgs.Arg("separator"), SqlFunctionArgs.Arg("arg1")], SqlFunctionArgs.ParamsArg("argOthers")),
            new PassThroughValueFunction("DIFFERENCE", [SqlFunctionArgs.Arg("character_expression1"), SqlFunctionArgs.Arg("character_expression2")]),
            new PassThroughValueFunction("FORMAT", SqlFunctionArgs.Arg("value"), SqlFunctionArgs.Arg("format"), SqlFunctionArgs.Arg("culture", optional: true)),
            new PassThroughValueFunction("LEN", SqlFunctionArgs.Arg("string_expression")),
            new PassThroughValueFunction("LOWER", SqlFunctionArgs.Arg("string_expression")),
            new PassThroughValueFunction("LTRIM", SqlFunctionArgs.Arg("string_expression")),
            new PassThroughValueFunction("NCHAR", SqlFunctionArgs.Arg("integer_expression")),
            new PassThroughValueFunction("PATINDEX", SqlFunctionArgs.Arg("pattern"), SqlFunctionArgs.Arg("expression")),
            new PassThroughValueFunction("RTRIM", SqlFunctionArgs.Arg("string_expression")),
            new PassThroughValueFunction("TRIM", SqlFunctionArgs.Arg("string_expression")),
            new PassThroughValueFunction("SUBSTRING", SqlFunctionArgs.Arg("expression"), SqlFunctionArgs.Arg("start"), SqlFunctionArgs.Arg("length", optional: true)),
            new PassThroughValueFunction("ROLLUP", [SqlFunctionArgs.Arg("expression")], SqlFunctionArgs.ParamsArg("expression")),
            new PassThroughValueFunction("CUBE", [SqlFunctionArgs.Arg("expression")], SqlFunctionArgs.ParamsArg("expression")),
            new PassThroughValueFunction("CONVERT", SqlFunctionArgs.Arg("datatype", skipBinding: true), SqlFunctionArgs.Arg("expression"), SqlFunctionArgs.Arg("style", optional: true)),
            new PassThroughValueFunction("CAST", SqlFunctionArgs.Arg("as_expression", requiredType: typeof(AsExpression))),
            new PassThroughValueFunction("PARSE", SqlFunctionArgs.Arg("as_expression", requiredType: typeof(AsExpression))),
            new PassThroughValueFunction("TRY_CAST", SqlFunctionArgs.Arg("as_expression", requiredType: typeof(AsExpression))),
            new PassThroughValueFunction("TRY_PARSE", SqlFunctionArgs.Arg("as_expression", requiredType: typeof(AsExpression))),
            new PassThroughValueFunction("TRY_CONVERT", SqlFunctionArgs.Arg("datatype", skipBinding: true), SqlFunctionArgs.Arg("expression"), SqlFunctionArgs.Arg("style", optional: true)),
        ];
}
