name: Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - "*"
  release:
    types: [created]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # so auto package version numbers work as expected
    
      - name: Test
        run: dotnet test

      - name: Package
        run: dotnet pack -o .

      - uses: actions/upload-artifact@v4
        with:
          name: "packages"
          path: |
            ./*.nupkg
          retention-days: 1

      # get api key and push to nuget.org if this is a release event
      - name: NuGet login (OIDC → temp API key)
        if: (github.event_name == 'release' && github.event.action == 'created')
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: NuGet push
        if: (github.event_name == 'release' && github.event.action == 'created')
        run: dotnet nuget push ./*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
